# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: p2p/proto/forward.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'p2p/proto/forward.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17p2p/proto/forward.proto\x12\x08gradient\"5\n\x06Tensor\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\x12\x0c\n\x04size\x18\x02 \x03(\r\x12\r\n\x05\x64type\x18\x03 \x01(\t\"=\n\x0bNamedTensor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12 \n\x06tensor\x18\x02 \x01(\x0b\x32\x10.gradient.Tensor\"?\n\x15PPProxyTensorsMessage\x12&\n\x07tensors\x18\x01 \x03(\x0b\x32\x15.gradient.NamedTensor\"\xa7\x02\n\x0eSamplingParams\x12\x16\n\x0emax_new_tokens\x18\x01 \x01(\x05\x12\x16\n\x0emin_new_tokens\x18\x02 \x01(\x05\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\r\n\x05top_p\x18\x04 \x01(\x02\x12\r\n\x05min_p\x18\x05 \x01(\x02\x12\r\n\x05top_k\x18\x06 \x01(\x05\x12\x16\n\x0estop_token_ids\x18\x07 \x03(\x05\x12\x12\n\nignore_eos\x18\x08 \x01(\x08\x12\x11\n\tstop_strs\x18\t \x03(\t\x12\x1a\n\x12repetition_penalty\x18\n \x01(\x02\x12\x18\n\x10presence_penalty\x18\x0b \x01(\x02\x12\x19\n\x11\x66requency_penalty\x18\x0c \x01(\x02\x12\x13\n\x0bjson_schema\x18\r \x01(\t\"\x86\x01\n\x03Req\x12\x0b\n\x03rid\x18\x01 \x01(\t\x12\x15\n\routput_length\x18\x02 \x01(\x05\x12\x15\n\rrouting_table\x18\x03 \x03(\t\x12\x11\n\tinput_ids\x18\x04 \x03(\x05\x12\x31\n\x0fsampling_params\x18\x05 \x01(\x0b\x32\x18.gradient.SamplingParams\"\xad\x01\n\x0e\x46orwardRequest\x12+\n\x0c\x66orward_mode\x18\x01 \x01(\x0e\x32\x15.gradient.ForwardMode\x12\x1b\n\x04reqs\x18\x02 \x03(\x0b\x32\r.gradient.Req\x12\x16\n\x0enext_token_ids\x18\x03 \x03(\x05\x12\x39\n\x10pp_proxy_tensors\x18\x04 \x01(\x0b\x32\x1f.gradient.PPProxyTensorsMessage\"\x11\n\x0f\x46orwardResponse*0\n\x0b\x46orwardMode\x12\n\n\x06\x45XTEND\x10\x00\x12\n\n\x06\x44\x45\x43ODE\x10\x01\x12\t\n\x05MIXED\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p2p.proto.forward_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FORWARDMODE']._serialized_start=850
  _globals['_FORWARDMODE']._serialized_end=898
  _globals['_TENSOR']._serialized_start=37
  _globals['_TENSOR']._serialized_end=90
  _globals['_NAMEDTENSOR']._serialized_start=92
  _globals['_NAMEDTENSOR']._serialized_end=153
  _globals['_PPPROXYTENSORSMESSAGE']._serialized_start=155
  _globals['_PPPROXYTENSORSMESSAGE']._serialized_end=218
  _globals['_SAMPLINGPARAMS']._serialized_start=221
  _globals['_SAMPLINGPARAMS']._serialized_end=516
  _globals['_REQ']._serialized_start=519
  _globals['_REQ']._serialized_end=653
  _globals['_FORWARDREQUEST']._serialized_start=656
  _globals['_FORWARDREQUEST']._serialized_end=829
  _globals['_FORWARDRESPONSE']._serialized_start=831
  _globals['_FORWARDRESPONSE']._serialized_end=848
# @@protoc_insertion_point(module_scope)
